name: Daily Stock Scanner

on:
  schedule:
    - cron: '30 13 * * 1-5'
    - cron: '0 14 * * 1-5'
    - cron: '30 14 * * 1-5'
    - cron: '0 15 * * 1-5'
    - cron: '30 15 * * 1-5'
    - cron: '0 16 * * 1-5'
    - cron: '30 16 * * 1-5'
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scanner
        env:
          POLYGON_KEY: ${{ secrets.POLYGON_KEY }}
          FINNHUB_KEY: ${{ secrets.FINNHUB_KEY }}
          NEWSAPI_KEY: ${{ secrets.NEWSAPI_KEY }}
        run: python test_05_scanner.py

      - name: Commit results
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add -A
          git commit -m "Scan: $(date)" || true
          git push
