name: Daily Stock Scanner - Production (6 Providers, 9 Scans/Day)

on:
  schedule:
    # Pre-market: 8:30 AM ET (1:30 PM UTC)
    - cron: '30 13 * * 1-5'
    # 9:30 AM ET
    - cron: '30 14 * * 1-5'
    # 10:30 AM ET
    - cron: '30 15 * * 1-5'
    # 11:30 AM ET
    - cron: '30 16 * * 1-5'
    # 12:30 PM ET
    - cron: '30 17 * * 1-5'
    # 1:30 PM ET
    - cron: '30 18 * * 1-5'
    # 2:30 PM ET
    - cron: '30 19 * * 1-5'
    # 3:30 PM ET
    - cron: '30 20 * * 1-5'
    # 4:30 PM ET
    - cron: '30 21 * * 1-5'
  
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run production scanner (5000 US stocks, 6 providers)
        env:
          POLYGON_KEY: ${{ secrets.POLYGON_KEY }}
          FINNHUB_KEY: ${{ secrets.FINNHUB_KEY }}
          TWELVE_DATA_KEY: ${{ secrets.TWELVE_DATA_KEY }}
          FMP_KEY: ${{ secrets.FMP_KEY }}
          TIINGO_KEY: ${{ secrets.TIINGO_KEY }}
          ALPHA_VANTAGE_KEY: ${{ secrets.ALPHA_VANTAGE_KEY }}
          NEWSAPI_KEY: ${{ secrets.NEWSAPI_KEY }}
        run: |
          python -m src.analysis.scanner_final \
            --tickers data/tickers_5000.csv \
            --output-dir data/output \
            --batch-size 100 \
            --workers 6 \
            --days 30 \
            --threshold 50

      - name: Generate Dashboard
     
