name: Daily Stock Scanner - Production

on:
  workflow_dispatch:
  schedule:
    - cron: '0 14 * * 1-5'

permissions:
  contents: write

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GIT_TOKEN_CUSTOM }}
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          pip install pandas numpy yfinance requests ta-lib-bin
      
      - name: Run scanner
        env:
          FINNHUB_KEY: ${{ secrets.FINNHUB_KEY }}
          TWELVEDATA_KEY: ${{ secrets.TWELVEDATA_KEY }}
          FMP_KEY: ${{ secrets.FMP_KEY }}
          POLYGON_KEY: ${{ secrets.POLYGON_KEY }}
          TIINGO_KEY: ${{ secrets.TIINGO_KEY }}
          ALPHAVANTAGE_KEY: ${{ secrets.ALPHAVANTAGE_KEY }}
        run: python src/analysis/scanner_final.py
      
      - name: Generate dashboard
        run: python -c "from src.visualization.dashboard_generator import generate_dashboard; generate_dashboard('data/output/scan_results_latest.csv')"
      
      - name: Commit results
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add data/output/*
          git commit -m "Scan: $(date +'%Y-%m-%d %H:%M UTC')" || echo "No changes"
          git push
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: scan-results
          path: |
            data/output/scan_results_latest.csv
            data/output/dashboard.html
